name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x' # Defina a versão do .NET que você está usando

      - name: Install dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish --configuration Release --output ./publish

      - name: Deploy (exemplo, ajuste conforme necessário)
        run: |
          echo "Deploying to production..."
          # Adicione seu script de deploy aqui
