name: .NET CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Baixar o repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configurar o Cache do NuGet
      - name: Cache NuGet packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # Configurar o SDK do .NET
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'  # Defina a versão conforme o seu projeto

      # Restaurar os pacotes NuGet
      - name: Restore NuGet packages
        run: dotnet restore

      # Limpar o projeto
      - name: Clean project
        run: dotnet clean

      # Compilar o projeto
      - name: Build project
        run: dotnet build --no-restore --configuration Release
